### 결제
POST http://localhost:8080/v1/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiIxIiwiZW1haWwiOiJoaUBuYXZlci5jb20iLCJpc3MiOiJmY19taW5pIiwiaWF0IjoxNzAxMjIyMTkyLCJleHAiOjE3MDEyNTgxOTJ9.ap1luVnoPobJYE4fGJ5a_3uJi13xP_TMw5CniYfmzl0swAe7ZazMJ0RKUe-n-Zf6_sRHTR2CYP5h6H-YUPrLVA

[
  {
    "accommodation_id": 1,
    "people_number": 2,
    "start_date": "2023-12-01",
    "end_date": "2023-12-02",
    "representative_name": "홍길동",
    "representative_email": "rlfehd@naver.com",
    "order_price": 120000,
    "cart_id": 0
  }
]