version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: /home/ubuntu/server/scripts/move_server_jar.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/server/scripts/start_server.sh
      timeout: 60
      runas: ubuntu