spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:${LOCAL_MYSQL_TEST_PORT}/fc_mini?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true

service:
  jwt:
    secret-key: kj23h523kj5h24o1209481230948fsdfkljut90dgd89f0s2kl3daisoudqiwouekjashdjkahjkaqwueyqouasioudklascxcvhjuopqfu9aduro3
    access-expiration: 36000000
    refresh-expiration: 864000000