spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    org.springframework.security: debug