spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:tc:mysql:8.0://fc_mini?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
