spring:
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  file:
    name: gamsung-backend.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
