### 장바구니 등록
DELETE http://localhost:8080/v1/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiIxIiwiZW1haWwiOiJwZ3cxMTExMTFAbmF2ZXIuY29tIiwiaXNzIjoiZmNfbWluaSIsImlhdCI6MTcwMjU0MzQ0MywiZXhwIjoxNzAyNTc5NDQzfQ.N2W2ok0PMBrziXItQbeF-7K8uSYUWFhoIteGfXbwlI-HaKF3YvbGLLWOVqaImtnV7j2iLMjtUslfH41iCU0VJA

{
  "delete_id": [2]
}