### 장바구니 등록
POST http://localhost:8080/v1/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiI1MiIsImVtYWlsIjoibXl0ZXN0MUBuYXZlci5jb20iLCJpc3MiOiJmY19taW5pIiwiaWF0IjoxNzAxMjQyMzc2LCJleHAiOjE3MDEyNzgzNzZ9.k-iDVqJs7BWGkwr7A1dT_lVSOXn1T5lXqqvfzJqoofiptkOvZ8LpC---CiILeqKkIFgCVOOIIxfkmiJqf48Dlw

{
    "accommodation_id": 22,
    "name": "테스트대표",
    "address": "짧게나갈거",
    "start_date": "2023-11-29",
    "end_date": "2023-11-30",
    "people": 1,
    "cart_price": 130000,
    "accommodation_img": "테스트이미지url"
}